### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by teresalisanti** [Youssef-Harby/Remote-sensing-building-extraction-to-3D-model-using-Paddle-and-Grasshopper#1]
Hi :) I do not have a GPU to train a model for building footprint extraction. Can you provide me a pretrained model? So that i can directly run the predict command. Thank you

**Comment by gmommi** [comment]
It would be nice if you can provide the weights of the model to me too. Thanks!

**Comment by yharby** [comment]
Hi @teresalisanti and @gmommi, 
You can download the pretrained model from this link:
https://drive.google.com/drive/folders/1pTIFlBqQLg1YapTHfyALBlud3zWIPHSO?usp=sharing
Thanks to @geoyee 

Thank you for reaching us!
